apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-iam-test-s3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eks-iam-test-s3
  template:
    metadata:
      labels:
        app: eks-iam-test-s3
    spec:
      serviceAccountName: iam-test
      containers:
      - name: eks-iam-test
        image: 292090429255.dkr.ecr.ap-south-1.amazonaws.com/argocd:latest
        securityContext:
          privileged: true
